import javafx.scene.control.ScrollPane;
import javafx.scene.layout.GridPane;
import javafx.scene.text.Text;

// This pane records the result generated by area calculator
public class AreaRecordPane extends ScrollPane {

    final int scrollPWidth = 250;
    final int scrollPHeight = 300;

    final int recordsWidth = 240;

    GridPane recordsGrid = new GridPane();
    private int recordNum = 0;

    AreaRecordPane() {
        this.getStylesheets().add("Style.css");

        this.setWidth(scrollPWidth);
        this.setHeight(scrollPHeight);
        recordsGrid.setMaxWidth(recordsWidth);
        recordsGrid.setMinWidth(recordsWidth);
        //recordsGrid.setHgap(15);
        this.setContent(recordsGrid);
        this.getStyleClass().add("scroll") ;

    }

    // This is used to renew the result
    void addRecord(int area, int ppm) {
        Text record = new Text();
        record.getStyleClass().add("TextForArea");
        String content = "Area is " + Integer.toString(area);
        record.setText(content);
        recordsGrid.add(record, 0,recordNum);
        recordNum++;

        Text recordppm = new Text();
        recordppm.getStyleClass().add("TextForArea");

        String ppmString = "ppm is " + Integer.toString(ppm);
        recordppm.setText(ppmString);
        recordsGrid.add(recordppm, 0,recordNum);
        recordNum++;

        Text recordboard = new Text();
        recordboard.getStyleClass().add("TextForArea");
        String boardline= "         ";
        recordboard.setText(boardline);
        recordsGrid.add(recordboard, 0,recordNum);
        recordNum++;


    }
}
